// Code generated by MockGen. DO NOT EDIT.
// Source: ./core/tools/providers/jwt/jwt_provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jwt "github.com/martinsd3v/planets/core/tools/providers/jwt"
)

// MockIJwtProvider is a mock of IJwtProvider interface.
type MockIJwtProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIJwtProviderMockRecorder
}

// MockIJwtProviderMockRecorder is the mock recorder for MockIJwtProvider.
type MockIJwtProviderMockRecorder struct {
	mock *MockIJwtProvider
}

// NewMockIJwtProvider creates a new mock instance.
func NewMockIJwtProvider(ctrl *gomock.Controller) *MockIJwtProvider {
	mock := &MockIJwtProvider{ctrl: ctrl}
	mock.recorder = &MockIJwtProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJwtProvider) EXPECT() *MockIJwtProviderMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockIJwtProvider) CheckToken(tokenString string) (*jwt.TokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", tokenString)
	ret0, _ := ret[0].(*jwt.TokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockIJwtProviderMockRecorder) CheckToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockIJwtProvider)(nil).CheckToken), tokenString)
}

// CreateToken mocks base method.
func (m *MockIJwtProvider) CreateToken(payload jwt.TokenPayload) (*jwt.TokenDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", payload)
	ret0, _ := ret[0].(*jwt.TokenDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockIJwtProviderMockRecorder) CreateToken(payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockIJwtProvider)(nil).CreateToken), payload)
}
